import QueryProvider from "@/libs/react-query/QueryProvider";
import { Dancing_Script, Italiana, Playfair_Display } from "next/font/google";
import "./globals.css";

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-dancingScript",
});
const playfairDisplay = Playfair_Display({
  subsets: ["vietnamese"],
  variable: "--font-playFairDisplay",
});
const italiana = Italiana({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-italiana",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dancingScript.variable} ${playfairDisplay.variable} ${italiana.className} `}
      >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
