import QueryProvider from "@/libs/react-query/QueryProvider";
import ToastifyComponent from "@/libs/react-toastify/ToastifyComponent";
import { Dancing_Script, Italiana, Playfair_Display, Roboto_Condensed } from "next/font/google";
import "./globals.css";


const italiana = Italiana({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-italiana",
});
const roboto = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-roboto",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${italiana.className} `}
      >
        <QueryProvider>
          {children}
          <ToastifyComponent />
        </QueryProvider>
      </body>
    </html>
  );
}
